apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apps
  namespace: monitoring
  labels:
    name: apps
spec:
  selector:
    matchLabels:
     environment: prod
     type: monitor
  endpoints:
    - port: web